package com.mqq.activecufe;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.os.Bundle;
import android.webkit.WebView;
import android.widget.Toast;

public class TuijianJieActivity extends Activity {
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		// TODO Auto-generated method stub
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_webview);
		ConnectivityManager nw = (ConnectivityManager)this.getSystemService(Context.CONNECTIVITY_SERVICE);
	    NetworkInfo netinfo = nw.getActiveNetworkInfo();
	  WebView webview=(WebView) findViewById(R.id.webview);
		webview.getSettings().setJavaScriptEnabled(true);
		Intent intent=getIntent(); //获取开启此activity的意图对象
		//[3]获取那么和sex的值 小技巧：传递的是什么数据类型，这边是什么数据
		  String wenzi=intent.getStringExtra("wenzi");
		if(wenzi.equals("our广告社")){
			  TuijianJieActivity.this.setTitle("our广告社");
			  webview.loadUrl("http://mp.weixin.qq.com/s/ksu3psmITlauIa17xOlnSQ");  
		  }
		if(wenzi.equals("515交谊舞社")){
			TuijianJieActivity.this.setTitle("515交谊舞社");
			webview.loadUrl("http://mp.weixin.qq.com/s/mBUvtL-gW8zTbh4_pYSDzQ");
			  }
		if(wenzi.equals("安可歌唱社")){
			TuijianJieActivity.this.setTitle("安可歌唱社");
			webview.loadUrl("http://mp.weixin.qq.com/s/nxyNWqPvGYZwDcqbNipXbQ");
			 }
		if(wenzi.equals("博弈社")){
			TuijianJieActivity.this.setTitle("博弈社");
			webview.loadUrl("http://mp.weixin.qq.com/s/NCH8sNxSdYUAme_jeNTECw");
			 }
		if(wenzi.equals("BGC桌悦桌游社")){
			TuijianJieActivity.this.setTitle("BGC桌悦桌游社");
			webview.loadUrl("http://mp.weixin.qq.com/s/NekeDDPIsCJXZXL9dFJxng");
			 }
		if(wenzi.equals("北六环摇滚阵线")){
			TuijianJieActivity.this.setTitle("北六环摇滚阵线");
			webview.loadUrl("http://mp.weixin.qq.com/s/NClWNfbUg50evtbkMEy0Cw");
			  }
		if(wenzi.equals("逗你玩相声社")){
			TuijianJieActivity.this.setTitle("逗你玩相声社");
			webview.loadUrl("http://mp.weixin.qq.com/s/GLnpMsJh-zPtOLu02M1gpQ");
			 }
		if(wenzi.equals("风尚社")){
			TuijianJieActivity.this.setTitle("风尚社");
			webview.loadUrl("http://mp.weixin.qq.com/s/fYsBNiVefpOe5-X9m3tQrA");
			  }
		if(wenzi.equals("光影动漫社")){
			TuijianJieActivity.this.setTitle("光影动漫社");
			webview.loadUrl("http://mp.weixin.qq.com/s/9TRVxLwww7J0FsEiogQEZw");
			  }
		if(wenzi.equals("国乐社")){
			TuijianJieActivity.this.setTitle("国乐社");
			webview.loadUrl("http://mp.weixin.qq.com/s/KGquIurK0qEnnpT4Lrsq2Q");
			  }
		if(wenzi.equals("国球社")){
			TuijianJieActivity.this.setTitle("国球社");
			webview.loadUrl("http://mp.weixin.qq.com/s/qDqKo9eWZJvLBnA25FS9hw");
			  }
		if(wenzi.equals("翰墨书画社")){
			TuijianJieActivity.this.setTitle("翰墨书画社");
			webview.loadUrl("http://mp.weixin.qq.com/s/NwmKhxixk0bmYeFYFnPO0Q");
				  }
		if(wenzi.equals("和平鸽协会")){
			TuijianJieActivity.this.setTitle("和平鸽协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/Z9I-cxKu3gnDVn4C_nDe4g");
			  }
		if(wenzi.equals("吉他社")){
			TuijianJieActivity.this.setTitle("吉他社");
			webview.loadUrl("http://mp.weixin.qq.com/s/lGEUV6BGDC16I18_TwtHVA");
		 }
		if(wenzi.equals("经济人社团")){
			TuijianJieActivity.this.setTitle("经济人社团");
			webview.loadUrl("http://mp.weixin.qq.com/s/6qRfMK_HvVao2_-prcIsvw");
			}
		if(wenzi.equals("劲博武道社")){
			TuijianJieActivity.this.setTitle("劲博武道社");
			webview.loadUrl("http://mp.weixin.qq.com/s/EEIiYPYcayRjh7LpS38Q9g");
		 }
		if(wenzi.equals("KAB创业俱乐部")){
			TuijianJieActivity.this.setTitle("KAB创业俱乐部");
			webview.loadUrl("http://mp.weixin.qq.com/s/5-dVZ7iXChdc1jQaI4WH6A");
			 }
		if(wenzi.equals("酷飞篮球社")){
			TuijianJieActivity.this.setTitle("酷飞篮球社");
			webview.loadUrl("http://mp.weixin.qq.com/s/RheldGOiilYQAgw8tbDVQg");
			}
		if(wenzi.equals("科学幻想协会")){
			TuijianJieActivity.this.setTitle("科学幻想协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/8MAbBLVUmU9RNcvpKK87Mg");
			 }
		if(wenzi.equals("绿岩环保协会")){
			TuijianJieActivity.this.setTitle("绿岩环保协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/ze7QNVgdERamzVYnPwputA");
		 }
		if(wenzi.equals("轮滑社")){
			TuijianJieActivity.this.setTitle("轮滑社");
			webview.loadUrl("http://mp.weixin.qq.com/s/EjSgK1kC-c3rQWJmSCPSRQ");
			  }
		if(wenzi.equals("木木合气道社")){
			TuijianJieActivity.this.setTitle("木木合气道社");
			webview.loadUrl("http://mp.weixin.qq.com/s/qXef8gSSXGAkC-2nRIxZbQ");
			 }
		if(wenzi.equals("MC魔术社")){
			TuijianJieActivity.this.setTitle("MC魔术社");
			webview.loadUrl("http://mp.weixin.qq.com/s/rePuHv0Opx9qiR09x6LzoA");
			  }
		if(wenzi.equals("青春红丝带")){
			TuijianJieActivity.this.setTitle("青春红丝带");
			webview.loadUrl("http://mp.weixin.qq.com/s/BCGDJ-8XX_r2xQXb7wzcEw");
			  }
		if(wenzi.equals("Silence读书社")){
			TuijianJieActivity.this.setTitle("Silence读书社");
			webview.loadUrl("http://mp.weixin.qq.com/s/kjFVX5SFQQysE-HviDj9_Q");
			  }
		if(wenzi.equals("Shine-me模特社")){
			TuijianJieActivity.this.setTitle("Shine-me模特社");
			webview.loadUrl("http://mp.weixin.qq.com/s/GbasDTaVdlAvCWxEPfDu8Q");
			  }
		if(wenzi.equals("台球社")){
			TuijianJieActivity.this.setTitle("台球社");
			webview.loadUrl("http://mp.weixin.qq.com/s/n1QycZ24VJ38lWdT97A-pg");
			  }
		if(wenzi.equals("摄影社")){
			TuijianJieActivity.this.setTitle("摄影社");
			webview.loadUrl("http://mp.weixin.qq.com/s/UV_pup5A7w2if4bow4tH3w");
			  }
		if(wenzi.equals("TR网球社")){
			TuijianJieActivity.this.setTitle("TR网球社");
			webview.loadUrl("http://mp.weixin.qq.com/s/nVNc2L-BHTHMFk4ObrxjkA");
			  }
		if(wenzi.equals("未知心理社")){
			TuijianJieActivity.this.setTitle("未知心理社");
			webview.loadUrl("http://mp.weixin.qq.com/s/URMceVUKrU58mkXwMlTXVQ");
			  }
		if(wenzi.equals("维他户外运动社")){
			TuijianJieActivity.this.setTitle("维他户外运动社");
			webview.loadUrl("http://mp.weixin.qq.com/s/ugGFDU4ShCGVX9-XUtyLxw");
			  }
		if(wenzi.equals("未央舞社")){
			TuijianJieActivity.this.setTitle("未央舞社");
			webview.loadUrl("http://mp.weixin.qq.com/s/UZDtWleEHocvAbcfAw0Lew");
			  }
		if(wenzi.equals("校友工作志愿者协会")){
			TuijianJieActivity.this.setTitle("校友工作志愿者协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/SKamLlhEkovuHoPRxYNw0g");
			  }
		if(wenzi.equals("玄默汉服社")){
			TuijianJieActivity.this.setTitle("玄默汉服社");
			webview.loadUrl("http://mp.weixin.qq.com/s/3HG41FbtdKgD_gliWd1NvA");
			  }
		if(wenzi.equals("新长城自强社")){
			TuijianJieActivity.this.setTitle("新长城自强社");
			webview.loadUrl("http://mp.weixin.qq.com/s/owXsfXzeiPWfR3hj3XTp_w");
			  }
		if(wenzi.equals("新起点足球社")){
			TuijianJieActivity.this.setTitle("新起点足球社");
			webview.loadUrl("http://mp.weixin.qq.com/s/L-jy5_pM68CLgxsLLl85qA");
				  }
		if(wenzi.equals("艺社")){
			TuijianJieActivity.this.setTitle("艺社");
			webview.loadUrl("http://mp.weixin.qq.com/s/XLGzFuIcVy5JSR0vN5f6Og");
			  }
		if(wenzi.equals("羽毛球协会")){
			TuijianJieActivity.this.setTitle("羽毛球协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/63JJ105ZinH5c-EqJlMQ5Q");
			  }
		if(wenzi.equals("映画电影协会")){
			TuijianJieActivity.this.setTitle("映画电影协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/1zEcUp09QTfmX4VkhBYWpg");
			  }
		if(wenzi.equals("昭明文学社")){
			TuijianJieActivity.this.setTitle("昭明文学社");
			webview.loadUrl("http://mp.weixin.qq.com/s/bhEu_WeP9FLAK8KOaBP8Tg");
			  }
		if(wenzi.equals("中财idea精英汇")){
			TuijianJieActivity.this.setTitle("中财idea精英汇");
			webview.loadUrl("http://mp.weixin.qq.com/s/nvGpPVI500317XGaVgh5eA");
			  }
		if(wenzi.equals("财芸社")){
			TuijianJieActivity.this.setTitle("财芸社");
			webview.loadUrl("http://mp.weixin.qq.com/s/okSC6yk_aYcNJWfQalDe-w");
			  }
		if(wenzi.equals("e学社")){
			TuijianJieActivity.this.setTitle("e学社");
			webview.loadUrl("http://mp.weixin.qq.com/s/IsSDM13pvEX0Nv8ntQICzQ");
			  }
		if(wenzi.equals("瞭望社")){
			TuijianJieActivity.this.setTitle("瞭望社");
			webview.loadUrl("http://mp.weixin.qq.com/s/hi8EZrPFg9s6l6fvAerKsg");
			  }
		if(wenzi.equals("马克思主义研读社")){
			TuijianJieActivity.this.setTitle("马克思主义研读社");
			webview.loadUrl("http://mp.weixin.qq.com/s/kfdlPZ3hckh9Y-bI74LURg");
		  }
		if(wenzi.equals("缀思社")){
			TuijianJieActivity.this.setTitle("缀思社");
			webview.loadUrl("http://mp.weixin.qq.com/s/dJrBMY8wWdgWGXf3OwdMmQ");
			  }
		if(wenzi.equals("保险理论研究协会")){
			TuijianJieActivity.this.setTitle("保险理论研究协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/K1QFouJY7FBjQ9ab0K6OTg");
			  }
		if(wenzi.equals("调查分析协会")){
			TuijianJieActivity.this.setTitle("调查分析协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/12V-8EJi2_xvmQZfOAczBg");
		  }
		if(wenzi.equals("电子商务协会")){
			TuijianJieActivity.this.setTitle("电子商务协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/7n4QDgIzKw5dnXYwR_Yhfg");
			  }
		if(wenzi.equals("法学研究会")){
			TuijianJieActivity.this.setTitle("法学研究会");
			webview.loadUrl("http://mp.weixin.qq.com/s/lvPfSq_xtDTz9JZroud8KA");
			  }
		if(wenzi.equals("国际商务谈判协会")){
			TuijianJieActivity.this.setTitle("国际商务谈判协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/o4vNYaLg-TBGcBvwdkhdRA");
			  }
		if(wenzi.equals("公共管理研究会")){
			TuijianJieActivity.this.setTitle("公共管理研究会");
			webview.loadUrl("http://mp.weixin.qq.com/s/5Y9JqhUWwcNahn7atJJSgg");
			  }
		if(wenzi.equals("国贸学社")){
			TuijianJieActivity.this.setTitle("国贸学社");
			webview.loadUrl("http://mp.weixin.qq.com/s/vywdlv2nA33O_3FWg-enWQ");
			  }
		if(wenzi.equals("HR研究协会")){
			TuijianJieActivity.this.setTitle("HR研究协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/WQaRCnOi8Yo_6qbIOAXJMg");
			  }
		if(wenzi.equals("红叶国际关系学会")){
			TuijianJieActivity.this.setTitle("红叶国际关系学会（中财模联）");
			webview.loadUrl("http://mp.weixin.qq.com/s/YbGjXHprb8WotRgW1e60Ew");
			  }
		if(wenzi.equals("金融学术研究会")){
			TuijianJieActivity.this.setTitle("金融学术研究会");
			webview.loadUrl("http://mp.weixin.qq.com/s/KEpH_6YWJ8wr-jlitpW37Q");
			  }
		if(wenzi.equals("会计研究协会")){
			TuijianJieActivity.this.setTitle("会计研究协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/zLaVyhZjb-cx97KWEib5Ow");
			  }
		if(wenzi.equals("绿色金融国际研究协会")){
			TuijianJieActivity.this.setTitle("绿色金融国际研究协会");
				webview.loadUrl("http://mp.weixin.qq.com/s/fr_qAngdl2MrSZl2SenVxA");
			  }
		if(wenzi.equals("千帆数学社")){
					TuijianJieActivity.this.setTitle("千帆数学社");
					webview.loadUrl("http://mp.weixin.qq.com/s/Olkv6zCB73cmYr96IWQZuA");
					  }
		if(wenzi.equals("日语研究协会")){
			TuijianJieActivity.this.setTitle("日语研究协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/GBHp3wuGyaP3JnUwRCLLvA");
			  }
		if(wenzi.equals("融智创新俱乐部")){
			TuijianJieActivity.this.setTitle("融智创新俱乐部");
			webview.loadUrl("http://mp.weixin.qq.com/s/prGkIH5aMKyP26nelTgmfg");
			  }
		if(wenzi.equals("商务英语社")){
			TuijianJieActivity.this.setTitle("商务英语社");
			webview.loadUrl("http://mp.weixin.qq.com/s/ceUjrKnXIzW4wovsgazOwA");
				  }
		if(wenzi.equals("社会调查协会")){
			TuijianJieActivity.this.setTitle("社会调查协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/WrgkBx9_OBXrpOzOUYuAZQ");
				  }
		if(wenzi.equals("社会工作协会")){
			TuijianJieActivity.this.setTitle("社会工作协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/ORU-DWaXwRCLko589s8wnQ");
				  }
		if(wenzi.equals("英语协会")){
			TuijianJieActivity.this.setTitle("英语协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/vc-tk3QIwa36c80lc8ZxlA");
				  }
		if(wenzi.equals("税务研究会")){
			TuijianJieActivity.this.setTitle("税务研究会");
			webview.loadUrl("http://mp.weixin.qq.com/s/S8uQo-e19_PSMMn7n6ffgA");
			  }
		if(wenzi.equals("星火农村发展促进会")){
			TuijianJieActivity.this.setTitle("星火农村发展促进会");
			webview.loadUrl("http://mp.weixin.qq.com/s/LZJg-oFqVRZlyBJF4UOhSg");
				  }
		if(wenzi.equals("证券研究协会")){
			TuijianJieActivity.this.setTitle("证券研究协会");
			webview.loadUrl("http://mp.weixin.qq.com/s/N3fyDF0rz9HoyaRnaQ7_Ag");
				  }
		 

		
			
	}
	

}
